<?php echo $this->doctype(); ?>
<html lang="en" class="no-touch">
    <head>
        <meta charset="utf-8">
        <?php
            /**
             * Initialize Head title.
             */
            $this->headTitle('Atlas - '. $this->translate('CMS'))->setSeparator(' - ')->setAutoEscape(false);
            /**
             * Initialize Meta tags.
             */
            $this->omlZf2TM()->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
            $this->omlZf2TM()->headMeta()->appendName('description', $this->translate('NPM Technologies'));
            $this->omlZf2TM()->headMeta()->appendName('author', 'NPM');
            /**
             * Favico
             */
            // $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath($publicAssetPath).'images/favicon.ico'));
            // $this->headLink(array('rel' => 'apple-touch-icon', 'href' => '/apple-touch-icon.png'));
            /**
             * Load Theme Style List
             */
            // foreach ($themeCssStyles['css'] as $css) {
            //     $this->headLink()->appendStylesheet($this->basePath($themeCssStyles['styles_asset_path']).$css);
            // }

            /**
             * Render Head Elements.
             */
            echo $this->omlZf2TM()->headTitle();
            echo $this->omlZf2TM()->headMeta();
            echo $this->omlZf2TM()->headLink();
            echo $this->omlZf2TM()->headStyle();
            echo $this->omlZf2TM()->headScript();
        ?>
    </head>
    <body>
        <div id="preloader">
            <div id="status">
                <img src="<?php echo $this->omlZf2TM()->basePath('images/loader.gif'); ?>"/>
            </div>
        </div> 
        <section id="container">
            <aside>
                <div id="sidebar" class="nav-collapse">
                    <?php //echo $this->navigation('navigation')->menu()->setPartial('navigation/left'); ?>
                </div>
            </aside>
            <section id="main-content">
                <section class="wrapper">
                    <?php //echo $this->partial('toolbar'); ?>
                    <div class="wrapper_widget">
                        <div class="menu"></div>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="widgetitle">
                                        <div class="row">
                                            <?php echo $this->placeholder('widgets/page-info'); ?>
                                            <?php echo $this->placeholder('widgets/action-menu'); ?>
                                         </div>
                                    </div>
                                </div>
                            </div>
                            <?php echo $this->placeholder('widgets/breadcrumb'); ?>
                        </div>
                        <div class="container-fluid margin_bottom_xlarge margin_top_small">
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                </section>
            </section>
            <?php echo $this->placeholder('sidebar-right'); ?>
        </section>
    </body>
</html>